import { PrismaClient } from '@prisma/client';
import { hash } from 'bcryptjs';

const prisma = new PrismaClient();

const categories = [
  { name: 'Ficção', slug: 'ficcao', icon: '📖', description: 'Romances e narrativas ficcionais' },
  { name: 'Não-Ficção', slug: 'nao-ficcao', icon: '📚', description: 'Obras baseadas em fatos reais' },
  { name: 'Ciência', slug: 'ciencia', icon: '🔬', description: 'Divulgação científica e técnica' },
  { name: 'Tecnologia', slug: 'tecnologia', icon: '💻', description: 'Programação, IA e inovação' },
  { name: 'Negócios', slug: 'negocios', icon: '📈', description: 'Empreendedorismo e gestão' },
  { name: 'Filosofia', slug: 'filosofia', icon: '🤔', description: 'Pensamento crítico e reflexão' },
  { name: 'História', slug: 'historia', icon: '🏛️', description: 'Eventos e civilizações do passado' },
  { name: 'Biografias', slug: 'biografias', icon: '👤', description: 'Vidas de pessoas notáveis' },
  { name: 'Autoajuda', slug: 'autoajuda', icon: '🌟', description: 'Desenvolvimento pessoal' },
  { name: 'Fantasia', slug: 'fantasia', icon: '🐉', description: 'Mundos mágicos e aventuras épicas' },
  { name: 'Mistério', slug: 'misterio', icon: '🔍', description: 'Suspense e investigação' },
  { name: 'Romance', slug: 'romance', icon: '💕', description: 'Histórias de amor e relacionamentos' },
  { name: 'Terror', slug: 'terror', icon: '👻', description: 'Horror e sobrenatural' },
  { name: 'Infantil', slug: 'infantil', icon: '🧸', description: 'Literatura para crianças' },
  { name: 'Acadêmico', slug: 'academico', icon: '🎓', description: 'Textos acadêmicos e educacionais' },
  { name: 'Direito', slug: 'direito', icon: '⚖️', description: 'Legislação e jurisprudência' },
  { name: 'Medicina', slug: 'medicina', icon: '🏥', description: 'Saúde e ciências médicas' },
  { name: 'Arte e Design', slug: 'arte-design', icon: '🎨', description: 'Criatividade e expressão visual' },
  { name: 'Ciências Humanas', slug: 'ciencias-humanas', icon: '🧠', description: 'Psicologia, sociologia e antropologia' },
  { name: 'Economia', slug: 'economia', icon: '💰', description: 'Finanças e política econômica' },
];

const books = [
  {
    title: 'O Poder do Hábito',
    slug: 'o-poder-do-habito',
    author: 'Charles Duhigg',
    authorSlug: 'charles-duhigg',
    description: 'Charles Duhigg, repórter investigativo do The New York Times, desvenda a ciência por trás de por que os hábitos existem e como podem ser modificados. Com uma exploração fascinante de como hábitos influenciam nossas vidas, o livro revela como entender o ciclo hábito-liberação-recompensa pode transformar nossos comportamentos.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop',
    isbn: '978-8576654321',
    publisher: 'Objetiva',
    publishDate: '2012',
    language: 'pt-BR',
    pages: 408,
    fileSize: '2.8 MB',
    format: 'EPUB',
    rating: 4.5,
    ratingCount: 2847,
    downloadCount: 15420,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'nao-ficcao,autoajuda,negocios',
    tags: 'hábitos,psicologia,comportamento,transformação',
  },
  {
    title: 'A Revolução dos Bichos',
    slug: 'a-revolucao-dos-bichos',
    author: 'George Orwell',
    authorSlug: 'george-orwell',
    description: 'Uma fábula política satírica que conta a história de uma revolução animal em uma fazenda. Os animais decidem se livrar dos humanos e criam sua própria sociedade, mas logo descobrem que a igualdade que buscavam é ameaçada por aqueles que se encontram no poder.',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    isbn: '978-8535909557',
    publisher: 'Companhia das Letras',
    publishDate: '1945',
    language: 'pt-BR',
    pages: 152,
    fileSize: '1.2 MB',
    format: 'EPUB',
    rating: 4.7,
    ratingCount: 5621,
    downloadCount: 32100,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'ficcao,fantasia',
    tags: 'política,sociedade,distopia,fábula',
  },
  {
    title: 'Sapiens: Uma Breve História da Humanidade',
    slug: 'sapiens-uma-breve-historia-da-humanidade',
    author: 'Yuval Noah Harari',
    authorSlug: 'yuval-noah-harari',
    description: 'Yuval Noah Harari nos leva em uma jornada épica pela história da humanidade, desde os primeiros Homo sapiens até as revoluções científica, agrícola e tecnológica. Uma exploração fascinante de como fomos de primatas irrelevantes a senhores do mundo.',
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=600&fit=crop',
    isbn: '978-8525432186',
    publisher: 'Companhia das Letras',
    publishDate: '2015',
    language: 'pt-BR',
    pages: 464,
    fileSize: '3.1 MB',
    format: 'EPUB',
    rating: 4.8,
    ratingCount: 8934,
    downloadCount: 45200,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'historia,nao-ficcao,ciencias-humanas',
    tags: 'história,antropologia,evolução,civilização',
  },
  {
    title: 'Clean Code',
    slug: 'clean-code',
    author: 'Robert C. Martin',
    authorSlug: 'robert-c-martin',
    description: 'Um guia prático para escrever código limpo e elegante. Robert C. Martin apresenta princípios, padrões e boas práticas de programação que todo desenvolvedor deveria conhecer, com exemplos práticos em Java.',
    coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aadc?w=400&h=600&fit=crop',
    isbn: '978-0132350884',
    publisher: 'Prentice Hall',
    publishDate: '2008',
    language: 'en',
    pages: 464,
    fileSize: '4.5 MB',
    format: 'PDF',
    rating: 4.6,
    ratingCount: 3421,
    downloadCount: 28900,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'tecnologia,academico',
    tags: 'programação,boas-práticas,código,software',
  },
  {
    title: 'O Monge e o Executivo',
    slug: 'o-monge-e-o-executivo',
    author: 'James C. Scott',
    authorSlug: 'james-c-scott',
    description: 'Uma história sobre liderança, gestão e aprendizado organizacional. Através da metáfora de um mosteiro budista e um executivo de Wall Street, o livro explora como organizações podem se tornar mais eficazes e humanas.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
    isbn: '978-8573132441',
    publisher: 'Nobel',
    publishDate: '2004',
    language: 'pt-BR',
    pages: 272,
    fileSize: '1.8 MB',
    format: 'EPUB',
    rating: 4.3,
    ratingCount: 1234,
    downloadCount: 8700,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: false,
    categories: 'negocios,filosofia',
    tags: 'liderança,gestão,organizações',
  },
  {
    title: 'A Arte da Guerra',
    slug: 'a-arte-da-guerra',
    author: 'Sun Tzu',
    authorSlug: 'sun-tzu',
    description: 'O tratado militar mais antigo e influente do mundo, escrito há mais de 2.500 anos. Suas estratégias são amplamente aplicadas nos dias de hoje nos campos dos negócios, esportes e vida pessoal.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    isbn: '978-8572320276',
    publisher: 'Martin Claret',
    publishDate: '500 a.C.',
    language: 'pt-BR',
    pages: 128,
    fileSize: '0.8 MB',
    format: 'EPUB',
    rating: 4.4,
    ratingCount: 6789,
    downloadCount: 22100,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'filosofia,historia,negocios',
    tags: 'estratégia,liderança,filosofia,guerra',
  },
  {
    title: 'Introdução à Inteligência Artificial',
    slug: 'introducao-a-inteligencia-artificial',
    author: 'Stuart Russell',
    authorSlug: 'stuart-russell',
    description: 'O livro-texto mais utilizado em cursos de IA no mundo. Stuart Russell e Peter Norvig apresentam os fundamentos da inteligência artificial, desde algoritmos de busca até aprendizado de máquina e processamento de linguagem natural.',
    coverImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=600&fit=crop',
    isbn: '978-0136042594',
    publisher: 'Pearson',
    publishDate: '2020',
    language: 'en',
    pages: 1152,
    fileSize: '12.3 MB',
    format: 'PDF',
    rating: 4.7,
    ratingCount: 2156,
    downloadCount: 19800,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: false,
    categories: 'tecnologia,ciencia,academico',
    tags: 'inteligência artificial,machine learning,algoritmos',
  },
  {
    title: 'O Alquimista',
    slug: 'o-alquimista',
    author: 'Paulo Coelho',
    authorSlug: 'paulo-coelho',
    description: 'A jornada de Santiago, um jovem pastor espanhol que viaja até o Egito em busca de um tesouro enterrado. Uma alegoria poderosa sobre seguir seus sonhos e ouvir o coração.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    isbn: '978-8576653837',
    publisher: 'HarperCollins',
    publishDate: '1988',
    language: 'pt-BR',
    pages: 208,
    fileSize: '1.5 MB',
    format: 'EPUB',
    rating: 4.2,
    ratingCount: 12450,
    downloadCount: 56700,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'ficcao,fantasia',
    tags: 'aventura,espiritualidade,drama',
  },
  {
    title: 'Thinking, Fast and Slow',
    slug: 'thinking-fast-and-slow',
    author: 'Daniel Kahneman',
    authorSlug: 'daniel-kahneman',
    description: 'O Nobel de Economia Daniel Kahneman revela os dois sistemas que guiaram nossos pensamentos: o Sistema 1, rápido, intuitivo e emocional; e o Sistema 2, lento, deliberado e lógico. Uma obra que revolucionou nossa compreensão sobre tomada de decisão.',
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop',
    isbn: '978-0374533557',
    publisher: 'Farrar, Straus and Giroux',
    publishDate: '2011',
    language: 'en',
    pages: 499,
    fileSize: '3.8 MB',
    format: 'EPUB',
    rating: 4.6,
    ratingCount: 7823,
    downloadCount: 34500,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'ciencias-humanas,ciencia,nao-ficcao',
    tags: 'psicologia,economia,decisão,cognição',
  },
  {
    title: 'Neuromancer',
    slug: 'neuromancer',
    author: 'William Gibson',
    authorSlug: 'william-gibson',
    description: 'O romance que inaugurou o gênero cyberpunk. Case, um hacker de elite, é contratado para um último trabalho impossível que pode mudar o destino da humanidade. Uma visão profética do futuro da tecnologia e da sociedade.',
    coverImage: 'https://images.unsplash.com/photo-1614850523011-8f49ffc73908?w=400&h=600&fit=crop',
    isbn: '978-0441569595',
    publisher: 'Ace Books',
    publishDate: '1984',
    language: 'en',
    pages: 271,
    fileSize: '2.1 MB',
    format: 'EPUB',
    rating: 4.3,
    ratingCount: 3456,
    downloadCount: 12300,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: false,
    categories: 'ficcao,tecnologia',
    tags: 'cyberpunk,ficção científica,tecnologia,hacker',
  },
  {
    title: 'O Poder do Agora',
    slug: 'o-poder-do-agora',
    author: 'Eckhart Tolle',
    authorSlug: 'eckhart-tolle',
    description: 'Um guia para a iluminação espiritual que ensina como transcender o pensamento analítico e viver plenamente no momento presente. Eckhart Tolle compartilha suas experiências e ensinamentos sobre paz interior.',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    isbn: '978-8576654322',
    publisher: 'Pensamento',
    publishDate: '1997',
    language: 'pt-BR',
    pages: 236,
    fileSize: '1.6 MB',
    format: 'EPUB',
    rating: 4.5,
    ratingCount: 9876,
    downloadCount: 41200,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'autoajuda,filosofia',
    tags: 'mindfulness,espiritualidade,paz interior',
  },
  {
    title: 'Padrões de Projeto de Projetos de Software',
    slug: 'padroes-de-projeto-de-software',
    author: 'Erich Gamma',
    authorSlug: 'erich-gamma',
    description: 'O famoso "Gang of Four" apresenta 23 padrões de projeto essenciais para o desenvolvimento de software orientado a objetos. Uma obra fundamental para todo desenvolvedor de software.',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=600&fit=crop',
    isbn: '978-0201633610',
    publisher: 'Addison-Wesley',
    publishDate: '1994',
    language: 'en',
    pages: 395,
    fileSize: '5.2 MB',
    format: 'PDF',
    rating: 4.5,
    ratingCount: 2890,
    downloadCount: 16700,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: false,
    categories: 'tecnologia,academico',
    tags: 'design patterns,arquitetura,software,orientação a objetos',
  },
  {
    title: 'Sapiens: O Livro Ilustrado',
    slug: 'sapiens-livro-ilustrado',
    author: 'Yuval Noah Harari',
    authorSlug: 'yuval-noah-harari',
    description: 'Uma versão ilustrada e acessível do bestseller mundial. Com imagens deslumbrantes e texto adaptado, este livro traz a história da humanidade de forma visual e envolvente.',
    coverImage: 'https://images.unsplash.com/photo-1529473814998-077c879f9bde?w=400&h=600&fit=crop',
    isbn: '978-8525435354',
    publisher: 'Companhia das Letras',
    publishDate: '2020',
    language: 'pt-BR',
    pages: 336,
    fileSize: '45.2 MB',
    format: 'PDF',
    rating: 4.6,
    ratingCount: 1234,
    downloadCount: 7800,
    isFeatured: false,
    isNewRelease: true,
    isBestseller: false,
    categories: 'historia,nao-ficcao',
    tags: 'história,ilustrado,educativo',
  },
  {
    title: 'O Conteúdo é o Rei',
    slug: 'o-conteudo-e-o-rei',
    author: 'Bill Gates',
    authorSlug: 'bill-gates',
    description: 'Bill Gates compartilha sua visão sobre o futuro da tecnologia, educação e philanthropia. Um olhar inspirador sobre como a inovação pode transformar o mundo.',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&h=600&fit=crop',
    isbn: '978-8595081576',
    publisher: 'Objetiva',
    publishDate: '2021',
    language: 'pt-BR',
    pages: 320,
    fileSize: '2.9 MB',
    format: 'EPUB',
    rating: 4.4,
    ratingCount: 2345,
    downloadCount: 11200,
    isFeatured: false,
    isNewRelease: true,
    isBestseller: false,
    categories: 'tecnologia,nao-ficcao,biografias',
    tags: 'tecnologia,futuro,filantropia',
  },
  {
    title: 'Dom Casmurro',
    slug: 'dom-casmurro',
    author: 'Machado de Assis',
    authorSlug: 'machado-de-assis',
    description: 'Uma das obras-primas da literatura brasileira. Bentinho narra sua história de amor com Capitu, marcada por ciúmes e paranoia. Uma obra atemporal sobre a fragilidade da mente humana.',
    coverImage: 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=400&h=600&fit=crop',
    isbn: '978-8572320957',
    publisher: 'Martin Claret',
    publishDate: '1899',
    language: 'pt-BR',
    pages: 288,
    fileSize: '1.4 MB',
    format: 'EPUB',
    rating: 4.5,
    ratingCount: 8912,
    downloadCount: 38400,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'ficcao',
    tags: 'literatura brasileira,clássico,romance',
  },
  {
    title: 'O Cortiço',
    slug: 'o-cortico',
    author: 'Aluísio Azevedo',
    authorSlug: 'aluisio-azevedo',
    description: 'Um dos maiores romances naturalistas brasileiros. A vida no cortiço do Barão de Vila-Frigideira serve de palco para dramas humanos, vícios e a luta pela sobrevivência no Rio de Janeiro do século XIX.',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop',
    isbn: '978-8572322036',
    publisher: 'Martin Claret',
    publishDate: '1890',
    language: 'pt-BR',
    pages: 352,
    fileSize: '1.8 MB',
    format: 'EPUB',
    rating: 4.3,
    ratingCount: 4567,
    downloadCount: 18900,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: false,
    categories: 'ficcao',
    tags: 'literatura brasileira,naturalismo,clássico',
  },
  {
    title: 'O Mundo de Sofia',
    slug: 'o-mundo-de-sofia',
    author: 'Jostein Gaarder',
    authorSlug: 'jostein-gaarder',
    description: 'Uma introdução à filosofia contada através da história de Sofia, uma garota que recebe cartas misteriosos. Uma viagem pela história do pensamento filosófico ocidental.',
    coverImage: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop',
    isbn: '978-8572324597',
    publisher: 'Companhia das Letras',
    publishDate: '1991',
    language: 'pt-BR',
    pages: 534,
    fileSize: '2.4 MB',
    format: 'EPUB',
    rating: 4.6,
    ratingCount: 6789,
    downloadCount: 28900,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'filosofia,ficcao,academico',
    tags: 'filosofia,educação,jovens',
  },
  {
    title: 'Deep Learning',
    slug: 'deep-learning',
    author: 'Ian Goodfellow',
    authorSlug: 'ian-goodfellow',
    description: 'O guia definitivo para aprendizado profundo. Ian Goodfellow, Yoshua Bengio e Aaron Courville apresentam os fundamentos matemáticos e práticos das redes neurais profundas.',
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop',
    isbn: '978-0262035613',
    publisher: 'MIT Press',
    publishDate: '2016',
    language: 'en',
    pages: 800,
    fileSize: '18.5 MB',
    format: 'PDF',
    rating: 4.8,
    ratingCount: 3210,
    downloadCount: 24600,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: false,
    categories: 'tecnologia,ciencia,academico',
    tags: 'deep learning,redes neurais,machine learning,IA',
  },
  {
    title: 'O Conto da Aia',
    slug: 'o-conto-da-aia',
    author: 'Margaret Atwood',
    authorSlug: 'margaret-atwood',
    description: 'Em uma distopia onde mulheres são subjugadas, Offred narra sua vida na república de Gilead. Uma obra poderosa sobre poder, gênero e resistência que se tornou um ícone do feminismo.',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=600&fit=crop',
    isbn: '978-8535929661',
    publisher: 'Rocco',
    publishDate: '1985',
    language: 'pt-BR',
    pages: 368,
    fileSize: '2.3 MB',
    format: 'EPUB',
    rating: 4.4,
    ratingCount: 5432,
    downloadCount: 21800,
    isFeatured: false,
    isNewRelease: false,
    isBestseller: true,
    categories: 'ficcao,fantasia',
    tags: 'distopia,feminismo,distopia, ficção especulativa',
  },
  {
    title: 'Hábitos Atômicos',
    slug: 'habitos-atomicos',
    author: 'James Clear',
    authorSlug: 'james-clear',
    description: 'Um sistema comprovado para construir bons hábitos e quebrar os ruins. James Clear apresenta estratégias práticas baseadas em ciência para fazer pequenas mudanças que resultam em grandes transformações.',
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop',
    isbn: '978-8595080850',
    publisher: 'Objetiva',
    publishDate: '2018',
    language: 'pt-BR',
    pages: 320,
    fileSize: '2.5 MB',
    format: 'EPUB',
    rating: 4.7,
    ratingCount: 11234,
    downloadCount: 52300,
    isFeatured: true,
    isNewRelease: false,
    isBestseller: true,
    categories: 'autoajuda,nao-ficcao',
    tags: 'hábitos,produtividade,desenvolvimento pessoal',
  },
  {
    title: 'Arquitetura de Microsserviços',
    slug: 'arquitetura-de-microservicos',
    author: 'Sam Newman',
    authorSlug: 'sam-newman',
    description: 'Um guia completo para projetar e construir sistemas de microsserviços. Sam Newman aborda desde os fundamentos até estratégias avançadas de migração e operação.',
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=600&fit=crop',
    isbn: '978-1491950357',
    publisher: "O'Reilly",
    publishDate: '2021',
    language: 'en',
    pages: 326,
    fileSize: '6.8 MB',
    format: 'PDF',
    rating: 4.5,
    ratingCount: 1890,
    downloadCount: 13400,
    isFeatured: false,
    isNewRelease: true,
    isBestseller: false,
    categories: 'tecnologia,academico',
    tags: 'microsserviços,arquitetura,devops,cloud',
  },
];

async function main() {
  console.log('🗑️  Limpando dados de usuários...');
  await prisma.readStats.deleteMany();
  await prisma.download.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.review.deleteMany();
  await prisma.readingProgress.deleteMany();
  await prisma.readingList.deleteMany();
  await prisma.subscription.deleteMany();
  await prisma.session.deleteMany();
  await prisma.account.deleteMany();
  await prisma.user.deleteMany();

  console.log('📁 Verificando categorias...');
  const existingCategories = await prisma.category.count();
  if (existingCategories === 0) {
    for (const cat of categories) {
      await prisma.category.create({ data: cat });
    }
    console.log(`   Criadas ${categories.length} categorias`);
  } else {
    console.log(`   ${existingCategories} categorias já existem`);
  }

  console.log('📚 Verificando livros...');
  const existingBooks = await prisma.book.count();
  if (existingBooks === 0) {
    for (const book of books) {
      await prisma.book.create({ data: book });
    }
    console.log(`   Criados ${books.length} livros de exemplo`);
  } else {
    console.log(`   ${existingBooks} livros já existem`);
  }

  console.log('👤 Criando usuário admin...');
  const hashedPassword = await hash('admin123', 12);
  const adminUser = await prisma.user.create({
    data: {
      name: 'Administrador',
      email: 'admin@biblioteca.com',
      password: hashedPassword,
      role: 'admin',
    },
  });

  console.log('👤 Criando usuário demo...');
  const demoPassword = await hash('demo123', 12);
  const demoUser = await prisma.user.create({
    data: {
      name: 'Maria Silva',
      email: 'maria@exemplo.com',
      password: demoPassword,
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      role: 'user',
    },
  });

  console.log('💳 Criando assinatura demo...');
  await prisma.subscription.create({
    data: {
      userId: demoUser.id,
      plan: 'annual',
      status: 'active',
      currentPeriodStart: new Date(),
      currentPeriodEnd: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    },
  });

  console.log('📖 Criando dados de leitura demo...');
  const demoBooks = await prisma.book.findMany({ take: 5 });
  for (let i = 0; i < demoBooks.length; i++) {
    await prisma.readingProgress.create({
      data: {
        userId: demoUser.id,
        bookId: demoBooks[i].id,
        progress: Math.random() * 100,
        currentPage: Math.floor(Math.random() * 300),
        totalPages: demoBooks[i].pages || 300,
        lastReadAt: new Date(Date.now() - i * 24 * 60 * 60 * 1000),
      },
    });

    if (i < 3) {
      await prisma.readingList.create({
        data: {
          userId: demoUser.id,
          bookId: demoBooks[i].id,
          listType: 'reading',
        },
      });
    }

    if (i < 2) {
      await prisma.review.create({
        data: {
          userId: demoUser.id,
          bookId: demoBooks[i].id,
          rating: Math.floor(Math.random() * 2) + 4,
          comment: 'Excelente livro! Recomendo muito.',
        },
      });
    }
  }

  console.log('✅ Seed concluído com sucesso!');
  console.log('   Admin: admin@biblioteca.com / admin123');
  console.log('   Demo:  maria@exemplo.com / demo123');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
